CREATE TABLE IF NOT EXISTS Customers {
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    AGE TINYINT NOT NULL,
    ADDRESS TINYTEXT,
    LAST_VISITED DATETIME DEFAULT,
    LAST_UPDATED DATETIME DEFAULT ON UPDATE,
    CREATED_AT DATETIME DEFAULT,
    PRIMARY KEY (ID)
}

CREATE TABLE IF NOT EXISTS Items {
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PRICE FLOAT NOT NULL,
    PRIMARY KEY (ID)
}

CREATE TABLE IF NOT EXISTS Sales {
    ID INT NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customers(CUSTOMER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES Items(ITEM_ID)
}
